services:
  - type: web
    name: campusconnect
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVE_STATIC
        value: "true"
      - key: CLIENT_URL
        value: https://campusconnect-1-olvk.onrender.com
      - key: MONGO_URI
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_WEBHOOK_SECRET
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_FROM_NAME
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ARCJET_KEY
        sync: false
      - key: ARCJET_ENV
        sync: false
      - key: AZURE_SPEECH_KEY
        sync: false
      - key: AZURE_SPEECH_REGION
        sync: false
      - key: AZURE_TRANSLATOR_KEY
        sync: false
      - key: AZURE_TRANSLATOR_ENDPOINT
        sync: false
      - key: AZURE_TRANSLATOR_REGION
        sync: false
      - key: TEACHER_INVITE_CODE
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_KEY_PREFIX
        sync: campusconnect
